server:
  port: 8848
  tomcat:
    uri-encoding: utf-8
  shutdown: graceful

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
  config:
    import: classpath:febs.yml
  application:
    name: febs-shiro
    package-time: "@package-time@"
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: "/**"

mybatis-plus:
  type-aliases-package: cc.mrbird.febs.*.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty

logging:
  level:
    com:
      baomidou:
        mybatisplus:
          core:
            metadata:
              TableInfoHelper: error
